In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df =dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date']=pd.to_datetime(df['job_posted_date'])

c:\Users\Pc\anaconda3\envs\python_project\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# sample()

In [3]:
# sample method

df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
729692,Data Scientist,Analytics Engineer,Canada,via BeBee Canada,Full-time,False,Canada,2023-03-18 21:18:24,True,False,Canada,None,NaN,NaN,Canada Drives,"['sql', 'nosql', 'python', 'java', 'snowflake'...","{'analyst_tools': ['tableau'], 'cloud': ['snow..."
757581,Data Analyst,Creative Data Analyst,Dubai - United Arab Emirates,via Trabajo.org,Full-time,False,United Arab Emirates,2023-01-15 20:28:37,True,False,United Arab Emirates,None,NaN,NaN,TikTok,"['sql', 'python', 'oracle']","{'cloud': ['oracle'], 'programming': ['sql', '..."
206435,Business Analyst,Senior Associated Products Analyst Analyst,Qatar,via Trabajo.org,Full-time,False,Qatar,2023-03-17 23:08:27,False,False,Qatar,None,NaN,NaN,MphExperts,['flow'],{'other': ['flow']}
395184,Software Engineer,Software Engineer SWE I,Italy,via BeBee,Full-time,False,Italy,2023-05-07 18:59:21,False,False,Italy,None,NaN,NaN,WayUp,['flow'],{'other': ['flow']}
690185,Data Engineer,Data Engineer - Remote,Anywhere,via LinkedIn Hungary,Full-time,True,Hungary,2023-01-10 10:50:29,False,False,Hungary,None,NaN,NaN,Jobsgarden,"['sql', 'java', 'scala', 'python', 'r', 'snowf...","{'analyst_tools': ['power bi'], 'cloud': ['sno..."
220668,Software Engineer,"Frontend Engineer, Platform Experience (Vancou...",Canada (+1 other),via Splunk,Full-time,False,Canada,2023-11-17 22:12:59,True,False,Canada,None,NaN,NaN,Splunk,"['python', 'javascript', 'aws', 'azure', 'reac...","{'analyst_tools': ['splunk'], 'cloud': ['aws',..."
234806,Software Engineer,Software and Data Engineer,"San Francisco, CA",via AAAI Career Center,Full-time,False,Georgia,2023-05-13 08:04:16,True,False,United States,None,NaN,NaN,University of California San Francisco,"['python', 'sql', 'docker']","{'other': ['docker'], 'programming': ['python'..."
770423,Business Analyst,Sales Analyst,"Yerevan, Armenia",via JTI Jobs,Full-time,False,Armenia,2023-01-06 02:01:58,False,False,Armenia,None,NaN,NaN,JT International S.A.,"['word', 'excel']","{'analyst_tools': ['word', 'excel']}"
288770,Senior Data Engineer,Senior Data Engineer,"Austin, TX",via LinkedIn,Full-time,False,"New York, United States",2023-02-21 17:27:43,False,False,United States,None,NaN,NaN,Fractal,"['go', 'sql']","{'programming': ['go', 'sql']}"
609168,Business Analyst,Business Intelligence Specialist,"Guatemala City, Guatemala",via Trabajo.org,Full-time,False,Guatemala,2023-03-11 10:14:03,True,False,Guatemala,None,NaN,NaN,Tigo Guatemala,"['sql', 'python', 'java', 'javascript', 'r', '...","{'cloud': ['oracle'], 'programming': ['sql', '..."

# copy()

In [4]:
# loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df_original =dataset['train'].to_pandas()

In [5]:
df_original

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [8]:
# real example. I am creating a copy of data frame
df_altered=df_original.copy()

In [10]:
# Lets feel data in the blanks column of df_altered(salary_year_avg) without interfering with the original one
median_salary= df_altered['salary_year_avg'].median()
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)
df_altered.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [11]:
# lets check original df
df_original.loc[:10, 'salary_year_avg']

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
Name: salary_year_avg, dtype: float64